<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DogBreedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pet_breeds')->insert([
            ['breed' => 'Affenpinscher', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Afghan Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Airedale Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Akita', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Alaskan Klee Kai', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Alaskan Malamute', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Bulldog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American English Coonhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Eskino Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Foxhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Hairless Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Leopard Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Staffordshire Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'American Water Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Anatolian Shepherd Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Appenzeller Sennenhund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Aspin', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Australian Cattle Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Australian Kelpie', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Australian Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Australian Stumpy Tail Cattle Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Australian Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Azawakh', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Barbado da Terceira', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Barbet', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Basenji', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Basset Fauve de Bretagne', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Basset Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bavarian Mountain Scent Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Beagle', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bearded Collie', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Beauceron', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bedlington Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Belgian Laekenois', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Belgian Malinois', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Belgian Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Belgian Tervuren', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bergamasco Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Berger Picard', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bernese Mountain Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bichon Frise', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Biewer Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Black and Tan Coonhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Black Russian Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bloodhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Blue Picardy Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bluetick Coonhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Boerbel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bohemian Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bolognese', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Border Collie', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Border Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Borzoi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Boston Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bouvier des Ardennes', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bouvier des Flandres', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Boxer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Boykin Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bracco Italiano', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Braque du Bourbonnais', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Braque Francais Pyrenean', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Braque Saint Germain', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Brazillian Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Briard', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Brittany', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Broholmer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Brussels Griffon', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bull Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bulldog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Bullmastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cain Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Canaan Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Canadian Eskimo Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cane Corso', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cardian Welsh Corgi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Carolina Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Catahoula Leopard Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Caucasian Shepherd Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cavalier King Charles Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Central Asian Shepherd Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cesky Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chesapeake Bay Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chihuahua', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chinese Crested', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chinese Sharpei', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chinook', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Chow Chow', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cirneco dell`Etna', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Clumber Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Cocker Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Collie', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Coton de Tulear', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Croatian Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Curly-Coated Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Czechoslovakian Vlciak', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dachshund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dalmatian', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dandie Dinmont Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Danish-Swedish Farmdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Deutscher Wachtelhund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Doberman Pinscher', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dogo Argentino', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dogue de Bordeaux', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Drentsche Patrijshond', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Drever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Dutch Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'English Cocker Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'English Foxhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'English Setter', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'English Sprinver Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'English Toy Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Entlebucher Mountain Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Estrela Mountain Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Eurasier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Field Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Finnish Lapphund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Boxer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Finnish Spitz', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Flat-Coated Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'French Bulldog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'French Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Longhaired Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Pinscher', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Sheep Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Shorthaired Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Spitz', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'German Wirehaired Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Giant Schnauzer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Glen of Imaal Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Golden Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Gordon Setter', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Grand Basset Griffon Venden', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Great Dane', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Great Pyrenees', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Greater Swiss Mountain Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Greyhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Hamiltonstovare', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Hanoverian Scenthound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Harrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Havanese', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Hokkaido', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Hovawart', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Ibizan Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Icelandic Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Irish Red and White Setter', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Irish Setter', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Irish Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Irish Water Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Irish Wolfhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Italian Greyhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Jagdterrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Japanese Akitainu', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Japanese Chin', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Japanese Spitz', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Japanese Terriers', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Kai Ken', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Karelian Bear Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Keeshond', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Kerry Blue Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Kishu Ken', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Komondor', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Korean Jindo Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Kromfohrlander', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Kuvasz', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Labrador Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lagotton Romagnolo', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lakeland Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lancashire Heeler', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lapponian Herder', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Large Munsterlander', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Leonberger', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lhasa Apso', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Lwchen', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Maltese', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Manchester Terrier (Standard)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Manchester Terrier (Toy)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Mastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Miniature American Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Miniature Bull Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Miniature Pinscher', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Miniature Schnauzer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Mountain Cur', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Mudi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Mutt (Mixed Breed)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Neapolitan Mastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Nederlandse Kooikerhondje', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Newfoundland', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norfolk Terriers', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norrbottenspets', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norwegian Buhund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norwegian Elkhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norwegian Lundehund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Norwich Terriers', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Nova Scotia Duck Tolling Retriever', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Old English Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Other', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Otterhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Papillon', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Parson Russell Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pekingese', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pembroke Welsh Corgi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Peruvian Inca Orchid', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Petit Basset Griffon Venden', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pharaoh Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Plott Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Polish Lowland Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pomeranian', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pont-Audemer Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Poodle (Miniature)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Poodle (Standard)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Poodle (Toy)', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Porcelaine', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Portuguese Podengo', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Portuguese Podengo Pequeno', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Portuguese Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Portuguese Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Portuguese Water Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Presa Canario', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pudelpointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pug', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Puli', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pumi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pyrenean Mastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Pyrenean Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Rafeiro do Alentejo', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Rat Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Redbone Coonhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Rhodesian Ridgeback', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Romanian Carpathian Shepherd', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Romanian Mioritic Shepherd Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Rottweiler', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Russell Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Russian Toy', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Russkaya Tsvetnaya Bolonka', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Saint Bernard', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Saluki', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Samoyed', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Schapendoes', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Schipperke', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Scottish Deerhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Scottish Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Sealyham Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Segugio Italiano', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Shetland Sheepdog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Shiba Inu', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Shih Tzu', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Shikoku', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Siberian Husky', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Silky Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Skye Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Sloughi', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Slovakian Wirehaired Pointer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Slovensky Cuvac', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Slovensky Kopov', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Small Munsterlander', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Smooth Fox Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Soft Coated Wheaten Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Spanish Mastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Spanish Water Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Spinone Italiano', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Stabyhoun', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Staffordshire Bull Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Standard Schnauzer', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Sussex Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Swedish Lapphund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Swedish Vallhund', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Taiwan Dog', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Teddy Roosevelt Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Thai Bangkaew', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Thai Ridgeback', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Tibetan Mastiff', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Tibetan Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Tibetan Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Tornjak', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Tosa', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Toy Fox Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Transylvanian Hound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Treeing Tennessee Brindle', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Treeing Walker Coonhound', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Vizsla', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Volpino Italiano', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Weimaraner', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Weksh Springer Spaniel', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Welsh Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'West Highland White Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Wetterhoun', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Whippet', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Wire Fox Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Wirehaired Pointing Griffon', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Wirehaired Vizsla', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Working Kelpie', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Xoloitzcuintli', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Yakutian Laikas', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['breed' => 'Yorkshire Terrier', 'pet_type' => 1, 'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}
